import type { Metadata } from 'next';

import { Providers } from './providers';
import { fonts } from './font';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className={fonts.exo.variable}>
      <Providers>{children}</Providers>
    </html>
  )
}
